### ISSUE TITLE
The attempt to build the project failed

### ISSUE THREAD

**Issue by FredericInn** [Saar25/Lwjgl#3]
After viewing, I tried to build the project, and ran into a problem, some of the classes after copying cannot find the existing directories, and, accordingly, cannot use them in other classes.

I tried to clean up the project or try to compile it with my own script, it was also unsuccessful there. If you have a compiled version of the project, then that would be very opportunely.

I am currently studying at university and your repository can greatly help me learn ljwgl. 

I hope you take the time to answer, thank you.
![idea64_B2rsB2Zp6U](https://user-images.githubusercontent.com/70032005/116873639-774f6900-ac31-11eb-8326-ca88e8bac733.png)

**Comment by Saar25** [comment]
Seems like the kotlin files are missing, how do you build the project?

**Comment by FredericInn** [comment]
Kotlin is installed and another project builds with it gradle. I tried to compile through Maven scripts in "Lifecycle", And the method from IDEA in the project structure gives me a broken .jar

**Comment by Saar25** [comment]
you should use maven to build the project, not gradle
it seems odd that IntelliJ doesn't compile kotlin classes for you

in any case I have updated the pom xml so you can package to jar and run
please run the following commands:
```
mvn clean package
java -jar target/Lwjgl-1.0-SNAPSHOT.jar
```

**Comment by FredericInn** [comment]
Oh ... I think I'm doing something wrong. The new pom worked. The file was compiled, but then the resulting file either crashes immediately, or the hangs in the Windows Process Manager. I think I did not build the release correctly, here is the log: https://pastebin.com/bapAfYh5 

P.S. I apologize for the fact that the directories have crooked names (LJWGL - not LWJGL).

**Comment by Saar25** [comment]
it looks like the deploy script that failed, run `mvn package` instead of `mvn deploy`

**Comment by FredericInn** [comment]
Thanks, now it is created in the correct directory ... But still the question is, how can I run this, does it require any special arguments? The usual java -jar {name} .jar didn't work (works like the last attempt - hangs in the ram). :(

**Comment by Saar25** [comment]
Here is the jar file
https://www.mediafire.com/file/d05uxi4qmr4wng5/Lwjgl-1.0-SNAPSHOT.jar/file

try running it from the terminal (java -jar ...) and copy the error please

**Comment by FredericInn** [comment]
I found what was the problem, Java did not create itself an association to JAVA_HOME when reinstalling to 291 and because of this there were most of the startup problems. 

Today i find this stack: https://pastebin.com/mamVrWNa

**Comment by Saar25** [comment]
This is an error with opengl and your drivers
I can't really check it on my computer, but I believe this is the solution:
in some of the shaders there are constant arrays initialized
please try changing the syntax of each one from something like:
```
const vec2[] positions = {
    vec2(0, 1), vec2(0, 0),
    vec2(1, 1), vec2(1, 0)
};
```
to
```
const vec2[4] positions = vec2[](
    vec2(0, 1), vec2(0, 0),
    vec2(1, 1), vec2(1, 0)
);
```
(watch for the parentheses!)

those shaders are located in the paths:
resources/engine/postprocessing/gaussianblur/gaussianBlurFragment.glsl
resources/engine/tegui/render/GuiVertex.glsl

**Comment by FredericInn** [comment]
It worked.
Tried updating the drivers, but nothing changed.
Met this error again and changing the syntax helped.

Here is a stack, here the correctness of the input leads to the following: https://pastebin.com/py3JReAR

in engine.particles.particlesVert.glsl
`const float positions[8] = {
    -0.5f, +0.5f, -0.5f, -0.5f,
    +0.5f, +0.5f, +0.5f, -0.5f
};
`
to 

`const float positions[8] = (
    -0.5f, +0.5f, -0.5f, -0.5f,
    +0.5f, +0.5f, +0.5f, -0.5f
);
`

Without my changes this stack: - https://pastebin.com/jYcjFn5d

**Comment by Saar25** [comment]
Great!

I missed two more shaders,
do the same thing in
resources/engine/particles/particlesVert.glsl
resources/engine/postprocessing/simpleVertex.glsl

make sure you change it to
const float positions[8] = **float[]**( -0.5f, +0.5f, -0.5f, -0.5f, +0.5f, +0.5f, +0.5f, -0.5f );

**Comment by FredericInn** [comment]
Excellent! It works, thanks a lot for your help. Now I will learn further :)

**Comment by Saar25** [comment]
:))
I have added the changes to master
